import 'package:get/get.dart';

class LocaleString extends Translations{
  @override
  Map<String, Map<String, String>> get keys => {
    'uz_UZ':{
      'Dilshodjon Haydarov':'Dilshodjon Haydarov',
      'versiya':'Versiyasi 1.0.0',
      'Loyihalar ro‘yxati':'Loyihalar ro‘yxati',
      'Mening hisobim':'Mening hisobim',
      'Hisobdan chiqish':'Hisobdan chiqish',
      'Dastur mavzusi' : 'Dastur mavzusi',
      'Dastur tili' : 'Dastur tili',
      'Foydalanish yo‘riqnomasi' : 'Foydalanish yo‘riqnomasi',
      'Qo‘llab quvvatlash':'Qo‘llab quvvatlash',
      'Dasturni baholash' : 'Dasturni baholash',
      'Dasturni ulashish' : 'Dasturni ulashish',
      'Tahrirlash' : 'Tahrirlash',
      'Qidirish' : 'Qidirish',
      'Tilni tanlang' : 'Tilni tanlang',
      'Bog‘lanish' : 'Bog‘lanish',
      'Web sahifa' : 'Web sahifa',
      'Manzil' : 'Manzil',
      'Qo‘qon shaxar, A.Navoiy, 12 uy.' : 'Qo‘qon shaxar, A.Navoiy, 12 uy.',
      'Yuborildi' : 'Yuborildi',
      'Hisobni taxrirlash' : 'Hisobni taxrirlash',
      'Ism va familiya' : 'Ism va familiya',
      'Kiriting' : 'Kiriting',
      'Mamlakat' : 'Mamlakat',
      'Ism-familiyangizni kiriting' : 'Ism-familiyangizni kiriting',
      'Uzbekistan' : 'O‘zbekiston',
      'Viloyat' : 'Viloyat',
      'Shaxar/Tuman' : 'Shaxar/Tuman',
      'Foydalanuvchi turi' : 'Foydalanuvchi turi',
      'Xatolik' : 'Xatolik',
      'Xatolik yuz berdi' : 'Xatolik yuz berdi',
      'Iltimos, qayta urinib ko‘ring' : 'Iltimos, qayta urinib ko‘ring',
      'Viloyatni tanlang' : 'Viloyatni tanlang',
      'Shaxarni tanlang yoki Tumanni tanlang' : 'Shaxarni yoki Tumanni tanlang',
      'Saqlash' : 'Saqlash',
      'Ma’lumotlarni kiriting' : 'Ma’lumotlarni kiriting',

      'Kuzatuvchilar':'Kuzatuvchilar',
      'Ulashish':'Ulashish',
      'O‘chirish':'O‘chirish',
      'Jami':'Jami',
      'Yoniq':'Yoniq',
      'Xato':'Xato',
      'Qo‘shimcha ma’lumotlar yo‘q':'Qo‘shimcha ma’lumotlar yo‘q',

      //validation
      'Muvaffaqiyatli':'Muvaffaqiyatli',
      'Iltimos ulanishni tekshiring!': 'Iltimos ulanishni tekshiring!',
      'Hisobingizga kirishda xatolik yuz berdi.':'Hisobingizga kirishda xatolik yuz berdi.',
      'Serverga ulanishda xatolik yuz berdi.':'Serverga ulanishda xatolik yuz berdi.',
      'Ushbu foydalanuvchi hisobi o‘chirildi.':'Ushbu foydalanuvchi hisobi o‘chirildi.',
      'Sizda bunday huquq mavjud emas!':'Sizda bunday huquq mavjud emas!',
      'Ushbu foydalanuvchi allaqachon taklif qilgan.':'Ushbu foydalanuvchi allaqachon taklif qilgan.',
      'Ushbu foydalanuvchi tizimda mavjud emas!':'Ushbu foydalanuvchi tizimda mavjud emas!',
      'Kiritilgan ma’lumotlar (Masalan, seriya raqam) noto‘g‘ri!':'Kiritilgan ma’lumotlar (Masalan, seriya raqam) noto‘g‘ri!',
      'Ushbu loyiha boshqa foydalanuvchilarda mavjud.':'Ushbu loyiha boshqa foydalanuvchilarda mavjud.',
      'Bu qurilma online emas.':'Bu qurilma online emas.',
      'Ma’lumot o’zgartirildi.':'Ma’lumot o’zgartirildi.',
      'Iltimos hisobingizga qaytadan kiriting.': 'Iltimos hisobingizga qaytadan kiriting.',
      'Iltimos qaytadan urinib ko‘ring.': 'Iltimos qaytadan urinib ko‘ring.',
      'Qurilma qayta ishga tushdi.':'Qurilma qayta ishga tushdi.',
    },
    'en_EN':{
      'Dilshodjon Haydarov':'Dilshodjon Haydarov',
      'versiya':'Version 1.0.0',
    'Loyihalar ro‘yxati':'Project List',
    'Mening hisobim':'My Account',
    'Hisobdan chiqish':'Logout',
    'Dastur mavzusi':'App Theme',
    'Dastur tili':'App Language',
    'Foydalanish yo‘riqnomasi':'User Manual',
    'Qo‘llab quvvatlash':'Support',
    'Dasturni baholash':'Rate the App',
    'Dasturni ulashish':'Share the App',
    'Tahrirlash':'Edit',
    'Qidirish':'Search',
    'Tilni tanlang':'Choose Language',
    'Bog‘lanish':'Contact',
    'Web sahifa':'Website',
    'Manzil':'Address',
    'Qo‘qon shaxar, A.Navoiy, 12 uy.':'Qo‘qon city, A.Navoiy, 12 house.',
    'Yuborildi':'Sent',
    'Hisobni taxrirlash':'Edit Account',
    'Ism va familiya':'First Name and Last Name',
    'Kiriting':'Enter',
    'Mamlakat':'Country',
    'Ism-familiyangizni kiriting':'Enter your First Name and Last Name',
    'Uzbekistan':'Uzbekistan',
    'Viloyat':'Region',
    'Shaxar/Tuman':'City/District',
    'Foydalanuvchi turi':'User Type',
    'Xatolik':'Error',
    'Xatolik yuz berdi':'An Error Occurred',
    'Iltimos, qayta urinib ko‘ring':'Please Try Again',
    'Viloyatni tanlang':'Select Region',
    'Shaxarni tanlang yoki Tumanni tanlang':'Select City or District',
    'Saqlash':'Save',
    'Ma’lumotlarni kiriting':'Enter Information',

    'Kuzatuvchilar':'Followers',
    'Ulashish':'Share',
    'O‘chirish':'Delete',
    'Jami':'Total',
    'Yoniq':'On',
    'Xato':'Error',
    'Qo‘shimcha ma’lumotlar yo‘q':'No Additional Information',

    // validation
    'Muvaffaqiyatli':'Successful',
    'Iltimos ulanishni tekshiring!':'Please Check Your Connection!',
    'Hisobingizga kirishda xatolik yuz berdi.':'An Error Occurred While Logging Into Your Account.',
    'Serverga ulanishda xatolik yuz berdi.':'An Error Occurred Connecting to the Server.',
    'Ushbu foydalanuvchi hisobi o‘chirildi.':'This User Account Has Been Deleted.',
    'Sizda bunday huquq mavjud emas!':'You Do Not Have Such Permission!',
    'Ushbu foydalanuvchi allaqachon taklif qilgan.':'This User Has Already Been Invited.',
    'Ushbu foydalanuvchi tizimda mavjud emas!':'This User Does Not Exist in the System!',
    'Kiritilgan ma’lumotlar (Masalan, seriya raqam) noto‘g‘ri!':'The Entered Information (e.g., Serial Number) Is Incorrect!',
    'Ushbu loyiha boshqa foydalanuvchilarda mavjud.':'This Project Already Exists with Other Users.',
    'Bu qurilma online emas.':'This Device is Not Online.',
    'Ma’lumot o’zgartirildi.':'Information Has Been Changed.',
    'Iltimos hisobingizga qaytadan kiriting.':'Please Re-Login to Your Account.',
    'Iltimos qaytadan urinib ko‘ring.':'Please Try Again.',
    'Qurilma qayta ishga tushdi.':'Device Has Restarted.'
  },
    'ru_RU':{
      'Dilshodjon Haydarov':'Дильшоджон Хайдаров',
      'versiya':'Версия 1.0.0',
      'Loyihalar ro‘yxati':'Список проектов',
      'Mening hisobim':'Мой аккаунт',
      'Hisobdan chiqish':'Выйти из аккаунта',
      'Dastur mavzusi':'Тема приложения',
      'Dastur tili':'Язык приложения',
      'Foydalanish yo‘riqnomasi':'Руководство пользователя',
      'Qo‘llab quvvatlash':'Поддержка',
      'Dasturni baholash':'Оценить приложение',
      'Dasturni ulashish':'Поделиться приложением',
      'Tahrirlash':'Редактировать',
      'Qidirish':'Поиск',
      'Tilni tanlang':'Выберите язык',
      'Bog‘lanish':'Контакты',
      'Web sahifa':'Веб-сайт',
      'Manzil':'Адрес',
      'Qo‘qon shaxar, A.Navoiy, 12 uy.':'г. Коканд, ул. А.Навои, дом 12.',
      'Yuborildi':'Отправлено',
      'Hisobni taxrirlash':'Редактировать аккаунт',
      'Ism va familiya':'Имя и фамилия',
      'Kiriting':'Введите',
      'Mamlakat':'Страна',
      'Ism-familiyangizni kiriting':'Введите ваше имя и фамилию',
      'Uzbekistan':'Узбекистан',
      'Viloyat':'Регион',
      'Shaxar/Tuman':'Город/Район',
      'Foydalanuvchi turi':'Тип пользователя',
      'Xatolik':'Ошибка',
      'Xatolik yuz berdi':'Произошла ошибка',
      'Iltimos, qayta urinib ko‘ring':'Пожалуйста, попробуйте снова',
      'Viloyatni tanlang':'Выберите регион',
      'Shaxarni tanlang yoki Tumanni tanlang':'Выберите город или район',
      'Saqlash':'Сохранить',
      'Ma’lumotlarni kiriting':'Введите данные',

      'Kuzatuvchilar':'Подписчики',
      'Ulashish':'Поделиться',
      'O‘chirish':'Удалить',
      'Jami':'Итого',
      'Yoniq':'Включено',
      'Xato':'Ошибка',
      'Qo‘shimcha ma’lumotlar yo‘q':'Дополнительная информация отсутствует',

      // validation
      'Muvaffaqiyatli':'Успешно',
      'Iltimos ulanishni tekshiring!':'Пожалуйста, проверьте соединение!',
      'Hisobingizga kirishda xatolik yuz berdi.':'Ошибка при входе в аккаунт.',
      'Serverga ulanishda xatolik yuz berdi.':'Ошибка подключения к серверу.',
      'Ushbu foydalanuvchi hisobi o‘chirildi.':'Этот аккаунт удален.',
      'Sizda bunday huquq mavjud emas!':'У вас нет такого права!',
      'Ushbu foydalanuvchi allaqachon taklif qilgan.':'Этот пользователь уже приглашен.',
      'Ushbu foydalanuvchi tizimda mavjud emas!':'Этого пользователя нет в системе!',
      'Kiritilgan ma’lumotlar (Masalan, seriya raqam) noto‘g‘ri!':'Введенные данные (например, серийный номер) неверны!',
      'Ushbu loyiha boshqa foydalanuvchilarda mavjud.':'Этот проект уже существует у других пользователей.',
      'Bu qurilma online emas.':'Это устройство не в сети.',
      'Ma’lumot o’zgartirildi.':'Информация изменена.',
      'Iltimos hisobingizga qaytadan kiriting.':'Пожалуйста, войдите в аккаунт заново.',
      'Iltimos qaytadan urinib ko‘ring.':'Пожалуйста, попробуйте снова.',
      'Qurilma qayta ishga tushdi.':'Устройство перезапущено.'
    },
    'oz_OZ':{
      'Dilshodjon Haydarov':'Дилшоджон Ҳайдаров',
      'versiya':'Версия 1.0.0',
      'Loyihalar ro‘yxati':'Лойиҳалар рўйхати',
      'Mening hisobim':'Менинг ҳисобим',
      'Hisobdan chiqish':'Ҳисобдан чиқиш',
      'Dastur mavzusi':'Дастур мавзуси',
      'Dastur tili':'Дастур тили',
      'Foydalanish yo‘riqnomasi':'Фойдаланиш йўриқномаси',
      'Qo‘llab quvvatlash':'Қўллаб-қувватлаш',
      'Dasturni baholash':'Дастурни баҳолаш',
      'Dasturni ulashish':'Дастурни улашиш',
      'Tahrirlash':'Таҳрирлаш',
      'Qidirish':'Қидириш',
      'Tilni tanlang':'Тилни танланг',
      'Bog‘lanish':'Боғланиш',
      'Web sahifa':'Веб-саҳифа',
      'Manzil':'Манзил',
      'Qo‘qon shaxar, A.Navoiy, 12 uy.':'Қўқон шаҳар, А.Навоий, 12 уй.',
      'Yuborildi':'Юборилди',
      'Hisobni taxrirlash':'Ҳисобни таҳрирлаш',
      'Ism va familiya':'Исм ва фамилия',
      'Kiriting':'Киритинг',
      'Mamlakat':'Мамлакат',
      'Ism-familiyangizni kiriting':'Исм-фамилиянгизни киритинг',
      'Uzbekistan':'Ўзбекистон',
      'Viloyat':'Вилоят',
      'Shaxar/Tuman':'Шаҳар/Туман',
      'Foydalanuvchi turi':'Фойдаланувчи тури',
      'Xatolik':'Хатолик',
      'Xatolik yuz berdi':'Хатолик юз берди',
      'Iltimos, qayta urinib ko‘ring':'Илтимос, қайта уриниб кўринг',
      'Viloyatni tanlang':'Вилоятни танланг',
      'Shaxarni tanlang yoki Tumanni tanlang':'Шаҳарни ёки туманни танланг',
      'Saqlash':'Сақлаш',
      'Ma’lumotlarni kiriting':'Маълумотларни киритинг',

      'Kuzatuvchilar':'Кузатувчилар',
      'Ulashish':'Улашиш',
      'O‘chirish':'Ўчириш',
      'Jami':'Жами',
      'Yoniq':'Ёниқ',
      'Xato':'Хато',
      'Qo‘shimcha ma’lumotlar yo‘q':'Қўшимча маълумотлар йўқ',

      // validation
      'Muvaffaqiyatli':'Муваффақиятли',
      'Iltimos ulanishni tekshiring!':'Илтимос, уланишни текширинг!',
      'Hisobingizga kirishda xatolik yuz berdi.':'Ҳисобингизга киришда хатолик юз берди.',
      'Serverga ulanishda xatolik yuz berdi.':'Серверга уланишда хатолик юз берди.',
      'Ushbu foydalanuvchi hisobi o‘chirildi.':'Ушбу фойдаланувчи ҳисоби ўчирилди.',
      'Sizda bunday huquq mavjud emas!':'Сизда бундай ҳуқуқ мавжуд эмас!',
      'Ushbu foydalanuvchi allaqachon taklif qilgan.':'Ушбу фойдаланувчи аллақачон таклиф қилган.',
      'Ushbu foydalanuvchi tizimda mavjud emas!':'Ушбу фойдаланувчи тизимда мавжуд эмас!',
      'Kiritilgan ma’lumotlar (Masalan, seriya raqam) noto‘g‘ri!':'Киритилган маълумотлар (масалан, серия рақам) нотўғри!',
      'Ushbu loyiha boshqa foydalanuvchilarda mavjud.':'Ушбу лойиҳа бошқа фойдаланувчиларда мавжуд.',
      'Bu qurilma online emas.':'Бу қурилма онлайн эмас.',
      'Ma’lumot o’zgartirildi.':'Маълумот ўзгартирилди.',
      'Iltimos hisobingizga qaytadan kiriting.':'Илтимос, ҳисобингизга қайтадан киринг.',
      'Iltimos qaytadan urinib ko‘ring.':'Илтимос, қайтадан уриниб кўринг.',
      'Qurilma qayta ishga tushdi.':'Қурилма қайта ишга тушди.'
    }
  };

}