import 'package:get/get.dart';

class LocaleString extends Translations{
  @override
  Map<String, Map<String, String>> get keys => {
    'uz_UZ':{
      'Dilshodjon Haydarov':'Dilshodjon Haydarov',
      'versiya':'Versiyasi 1.0.0',
      'Loyihalar ro‘yxati':'Loyihalar ro‘yxati',
      'Mening hisobim':'Mening hisobim',
      'Hisobdan chiqish':'Hisobdan chiqish',
      'Dastur mavzusi' : 'Dastur mavzusi',
      'Dastur tili' : 'Dastur tili',
      'Foydalanish yo‘riqnomasi' : 'Foydalanish yo‘riqnomasi',
      'Qo‘llab quvvatlash':'Qo‘llab quvvatlash',
      'Dasturni baholash' : 'Dasturni baholash',
      'Dasturni ulashish' : 'Dasturni ulashish',
      'Tahrirlash' : 'Tahrirlash',
      'Qidirish' : 'Qidirish',
      'Tilni tanlang' : 'Tilni tanlang',
      'Bog‘lanish' : 'Bog‘lanish',
      'Web sahifa' : 'Web sahifa',
      'Manzil' : 'Manzil',
      'Qo‘qon shaxar, A.Navoiy, 12 uy.' : 'Qo‘qon shaxar, A.Navoiy, 12 uy.',
      'Yuborildi' : 'Yuborildi',
      'Hisobni taxrirlash' : 'Hisobni taxrirlash',
      'Ism va familiya' : 'Ism va familiya',
      'Kiriting' : 'Kiriting',
      'Mamlakat' : 'Mamlakat',
      'Ism-familiyangizni kiriting' : 'Ism-familiyangizni kiriting',
      'Uzbekistan' : 'O‘zbekiston',
      'Viloyat' : 'Viloyat',
      'Shaxar/Tuman' : 'Shaxar/Tuman',
      'Foydalanuvchi turi' : 'Foydalanuvchi turi',
      'Xatolik' : 'Xatolik',
      'Xatolik yuz berdi' : 'Xatolik yuz berdi',
      'Iltimos, qayta urinib ko‘ring' : 'Iltimos, qayta urinib ko‘ring',
      'Viloyatni tanlang' : 'Viloyatni tanlang',
      'Shaxarni tanlang yoki Tumanni tanlang' : 'Shaxarni yoki Tumanni tanlang',
      'Saqlash' : 'Saqlash',
      'Ma’lumotlarni kiriting' : 'Ma’lumotlarni kiriting',
      'Bekor qilish':'Bekor qilish',
      'Diqqat!':'Diqqat!',
      'Portlar holati':'Portlar holati',
      'Yaxshi':'Yaxshi',
      'Normal':'Normal',
      'Past':'Past',
      'O`chiq':'O`chiq',
      'Qurilma o‘chiq':'Qurilma o‘chiq',
      'Kuting!':'Kuting!',
      'Mamlakatlarni qidirish':'Mamlakatlarni qidirish',
      'Qurilma haqida':'Qurilma haqida',
      'Portlar holati haqida':'Portlar holati haqida',
      'ma’lumotlar':'ma’lumotlar',
      'Portlar':'Portlar',
      'Sozlamalar':'Sozlamalar',
      'Qurilma modeli':'Qurilma modeli',
      'Seriya raqami':'Seriya raqami',
      'MAC adress':'MAC Адрес',
      'Ip adress':'IP Адрес',
      'Dasturiy ta’minot':'Dasturiy ta’minot',
      'POE kuchlanishi':'POE кучлиги',
      'POE quvvati':'POE кучлиги',
      'Online davri':'Online даври',
      'Qurilmani o‘chirib yoqish':'Qurilmani o‘chirib yoqish',
      'Qurilmalar ro‘yxati':'Qurilmalar ro’yxati',
      'Ma’lumotlar topilmadi':'Ma’lumotlar topilmadi',
      'Port':'Port',
      'POE':'POE',
      'Extend':'Uzatish',
      'Reboot':'Qayta ishga tushirish',
      'Power':'Quvvat',
      'TX':'TX',
      'RX':'RX',
      'Status':'Holat',
      'Qurilmani tahrirlash':'Qurilmani tahrirlash',
      'Telefon raqamingizni kiriting':'Telefon raqamingizni kiriting:',
      'Biz Tasdiqlash kodini jo‘natamiz':'Biz Tasdiqlash kodini jo‘natamiz.',
      'Telefon raqam':'Telefon raqam',
      'Tasdiqlash':'Tasdiqlash',

      'Kuzatuvchilar':'Kuzatuvchilar',
      'Ulashish':'Ulashish',
      'O‘chirish':'O‘chirish',
      'Jami':'Jami',
      'Yoniq':'Yoniq',
      'Xato':'Xato',
      'Qo‘shimcha ma’lumotlar yo‘q':'Qo‘shimcha ma’lumotlar yo‘q',
      'Loyiha qo‘shish':'Loyiha qo‘shish',
      'Loyiha nomi': 'Loyiha nomi',
      'Qurilma nomi':'Qurilma nomi',
      'Qurilmaning ishlab chiqarish raqami':'Qurilmaning ishlab chiqarish raqami',
      'Qurilma paroli':'Qurilma paroli',
      'QR Kodni Skaynerlash':'QR Kodni Skaynerlash',
      'Loyihani tahrirlash':'Loyihani tahrirlash',
      'Qo‘shimcha ma’lumot':'Qo‘shimcha ma’lumot',
      'Loyihani kuzatuvchilari':'Loyihani kuzatuvchilari',
      'Loyihani ulashish':'Loyihani ulashish',
      'Kuzatuvchi telefon raqami':'Kuzatuvchi telefon raqami',
      'Kuzatuvchi nomi':'Kuzatuvchi nomi',
      'Loyiha o’chirilsinmi?':'Loyiha o’chirilsinmi?',
      'Qurilma o‘chirilsinmi?':'Qurilma o‘chirilsinmi?',

      //validation
      'Muvaffaqiyatli':'Muvaffaqiyatli',
      'Iltimos ulanishni tekshiring!': 'Iltimos ulanishni tekshiring!',
      'Hisobingizga kirishda xatolik yuz berdi.':'Hisobingizga kirishda xatolik yuz berdi.',
      'Serverga ulanishda xatolik yuz berdi.':'Serverga ulanishda xatolik yuz berdi.',
      'Ushbu foydalanuvchi hisobi o‘chirildi.':'Ushbu foydalanuvchi hisobi o‘chirildi.',
      'Sizda bunday huquq mavjud emas!':'Sizda bunday huquq mavjud emas!',
      'Ushbu foydalanuvchi allaqachon taklif qilgan.':'Ushbu foydalanuvchi allaqachon taklif qilgan.',
      'Ushbu foydalanuvchi tizimda mavjud emas!':'Ushbu foydalanuvchi tizimda mavjud emas!',
      'Kiritilgan ma’lumotlar (Masalan, seriya raqam) noto‘g‘ri!':'Kiritilgan ma’lumotlar (Masalan, seriya raqam) noto‘g‘ri!',
      'Ushbu loyiha boshqa foydalanuvchilarda mavjud.':'Ushbu loyiha boshqa foydalanuvchilarda mavjud.',
      'Bu qurilma online emas.':'Bu qurilma online emas.',
      'Ma’lumot o’zgartirildi.':'Ma’lumot o’zgartirildi.',
      'Iltimos hisobingizga qaytadan kiriting.': 'Iltimos hisobingizga qaytadan kiriting.',
      'Iltimos qaytadan urinib ko‘ring.': 'Iltimos qaytadan urinib ko‘ring.',
      'Qurilma qayta ishga tushdi.':'Qurilma qayta ishga tushdi.',
      'Loyiha nomini kiriting.':'Loyiha nomini kiriting.',
      'Qurilma nomini kiriting.':'Qurilma nomini kiriting.',
      'Qurilmaning ishlab chiqarish raqamini kiriting.':'Qurilmaning ishlab chiqarish raqamini kiriting.',
      'Qurilmaning parolini kiriting.':'Qurilmaning parolini kiriting.',
      'dialoglar':'Agar indikator sariq yoki to‘q sariq bo‘lsa, tarmoq kabelini va ulagichni tekshiring. uzoq masofali port funksiyasini yoqishga harakat qilib ko‘ring, chunki muammo liniyaning juda uzunligi yoki kabel sifatining yomonligi bilan bog‘liq bo‘lishi mumkin.'
    },
    'en_EN':{
      'Dilshodjon Haydarov':'Dilshodjon Haydarov',
      'versiya':'Version 1.0.0',
      'Loyihalar ro‘yxati':'Project List',
      'Mening hisobim':'My Account',
      'Hisobdan chiqish':'Log Out',
      'Dastur mavzusi':'Application Theme',
      'Dastur tili':'Application Language',
      'Foydalanish yo‘riqnomasi':'User Guide',
      'Qo‘llab quvvatlash':'Support',
      'Dasturni baholash':'Rate the Application',
      'Dasturni ulashish':'Share the Application',
      'Tahrirlash':'Edit',
      'Qidirish':'Search',
      'Tilni tanlang':'Select Language',
      'Bog‘lanish':'Contact',
      'Web sahifa':'Website',
      'Manzil':'Address',
      'Qo‘qon shaxar, A.Navoiy, 12 uy.':'Qo‘qon city, A.Navoiy street, house 12.',
      'Yuborildi':'Sent',
      'Hisobni taxrirlash':'Edit Account',
      'Ism va familiya':'First and Last Name',
      'Kiriting':'Enter',
      'Mamlakat':'Country',
      'Ism-familiyangizni kiriting':'Enter your first and last name',
      'Uzbekistan':'Uzbekistan',
      'Viloyat':'Region',
      'Shaxar/Tuman':'City/District',
      'Foydalanuvchi turi':'User Type',
      'Xatolik':'Error',
      'Xatolik yuz berdi':'An Error Occurred',
      'Iltimos, qayta urinib ko‘ring':'Please Try Again',
      'Viloyatni tanlang':'Select Region',
      'Shaxarni tanlang yoki Tumanni tanlang':'Select City or District',
      'Saqlash':'Save',
      'Ma’lumotlarni kiriting':'Enter Information',
      'Bekor qilish':'Cancel',
      'Diqqat!':'Attention!',
      'Portlar holati':'Port Status',
      'Yaxshi':'Good',
      'Normal':'Normal',
      'Past':'Low',
      'O`chiq':'Off',
      'Qurilma o‘chiq':'The device is off',
      'Kuting!':'Loading...',
      'Mamlakatlarni qidirish':'Search Regions',
      'Qurilma haqida':'About Device',
      'Portlar holati haqida':'About Ports',
      'ma’lumotlar':'Information',
      'Portlar':'Ports',
      'Sozlamalar':'Settings',
      'Qurilma modeli':'Device Model',
      'Seriya raqami':'Serial Number',
      'MAC adress':'MAC Address',
      'Ip adress':'IP Address',
      'Dasturiy ta’minot':'Software',
      'POE kuchlanishi':'POE Switch',
      'POE quvvati':'POE State',
      'Online davri':'Online Day',
      'Qurilmani o‘chirib yoqish':'Delete Device',
      'Qurilmalar ro‘yxati':'Device List',
      'Ma’lumotlar topilmadi':'Information Not Found',
      'Port':'Port',
      'POE':'POE',
      'Extend':'Extend',
      'Reboot':'Reboot',
      'Power':'Power',
      'TX':'TX',
      'RX':'RX',
      'Status':'Status',
      'Qurilmani tahrirlash':'Edit Device',
      'Telefon raqamingizni kiriting':'Enter your phone number:',
      'Biz Tasdiqlash kodini jo‘natamiz':'We will send you a verification code.',
      'Telefon raqam':'Phone Number',
      'Tasdiqlash':'Verify',

      'Kuzatuvchilar':'Followers',
      'Ulashish':'Share',
      'O‘chirish':'Delete',
      'Jami':'Total',
      'Yoniq':'On',
      'Xato':'Error',
      'Qo‘shimcha ma’lumotlar yo‘q':'No Additional Information',

      'Loyiha qo‘shish':'Add Project',
      'Loyiha nomi':'Project Name',
      'Qurilma nomi':'Device Name',
      'Qurilmaning ishlab chiqarish raqami':'Device Manufacturing Number',
      'Qurilma paroli':'Device Password',
      'QR Kodni Skaynerlash':'Scan QR Code',
      'Loyihani tahrirlash':'Edit Project',
      'Qo‘shimcha ma’lumot':'Additional Information',
      'Loyihani kuzatuvchilari':'Project Followers',
      'Loyihani ulashish':'Share Project',
      'Kuzatuvchi telefon raqami':'Follower Phone Number',
      'Kuzatuvchi nomi':'Follower Name',
      'Loyiha o’chirilsinmi?':'Delete Project?',
      'Qurilma o‘chirilsinmi?':'Delete Device?',

      // validation
      'Muvaffaqiyatli':'Successful',
      'Iltimos ulanishni tekshiring!':'Please Check Connection!',
      'Hisobingizga kirishda xatolik yuz berdi.':'Error Logging into Your Account.',
      'Serverga ulanishda xatolik yuz berdi.':'Error Connecting to the Server.',
      'Ushbu foydalanuvchi hisobi o‘chirildi.':'This User Account has Been Deleted.',
      'Sizda bunday huquq mavjud emas!':'You Do Not Have Such a Right!',
      'Ushbu foydalanuvchi allaqachon taklif qilgan.':'This User Has Already Been Invited.',
      'Ushbu foydalanuvchi tizimda mavjud emas!':'This User Does Not Exist in the System!',
      'Kiritilgan ma’lumotlar (Masalan, seriya raqam) noto‘g‘ri!':'The Entered Information (e.g., Serial Number) is Incorrect!',
      'Ushbu loyiha boshqa foydalanuvchilarda mavjud.':'This Project Already Exists for Other Users.',
      'Bu qurilma online emas.':'This Device is Not Online.',
      'Ma’lumot o’zgartirildi.':'Information has Been Changed.',
      'Iltimos hisobingizga qaytadan kiriting.':'Please Log in Again.',
      'Iltimos qaytadan urinib ko‘ring.':'Please Try Again.',
      'Qurilma qayta ishga tushdi.':'Device Restarted.',
      'Loyiha nomini kiriting.':'Enter Project Name.',
      'Qurilma nomini kiriting.':'Enter Device Name.',
      'Qurilmaning ishlab chiqarish raqamini kiriting.':'Enter Device Manufacturing Number.',
      'Qurilmaning parolini kiriting.':'Enter Device Password.',
      'Kuzatuvchi telefon raqami kiriting':'Enter Follower Phone Number',
      'Kuzatuvchi nomi kiriting':'Enter Follower Name',
      'dialoglar':'If the indicator is yellow or orange, check the network cable and connector. try enabling the long-distance port function, as the problem may be caused by the line being too long or the cable quality being poor.'
    },
    'ru_RU':{
      'Dilshodjon Haydarov':'Дильшоджон Хайдаров',
      'versiya':'Версия 1.0.0',
      'Loyihalar ro‘yxati':'Список проектов',
      'Mening hisobim':'Мой аккаунт',
      'Hisobdan chiqish':'Выйти из аккаунта',
      'Dastur mavzusi':'Тема приложения',
      'Dastur tili':'Язык приложения',
      'Foydalanish yo‘riqnomasi':'Руководство пользователя',
      'Qo‘llab quvvatlash':'Поддержка',
      'Dasturni baholash':'Оценить приложение',
      'Dasturni ulashish':'Поделиться приложением',
      'Tahrirlash':'Редактировать',
      'Qidirish':'Поиск',
      'Tilni tanlang':'Выберите язык',
      'Bog‘lanish':'Контакты',
      'Web sahifa':'Веб-сайт',
      'Manzil':'Адрес',
      'Qo‘qon shaxar, A.Navoiy, 12 uy.':'г. Коканд, ул. А.Навои, дом 12.',
      'Yuborildi':'Отправлено',
      'Hisobni taxrirlash':'Редактировать аккаунт',
      'Ism va familiya':'Имя и фамилия',
      'Kiriting':'Введите',
      'Mamlakat':'Страна',
      'Ism-familiyangizni kiriting':'Введите ваше имя и фамилию',
      'Uzbekistan':'Узбекистан',
      'Viloyat':'Регион',
      'Shaxar/Tuman':'Город/Район',
      'Foydalanuvchi turi':'Тип пользователя',
      'Xatolik':'Ошибка',
      'Xatolik yuz berdi':'Произошла ошибка',
      'Iltimos, qayta urinib ko‘ring':'Пожалуйста, попробуйте снова',
      'Viloyatni tanlang':'Выберите регион',
      'Shaxarni tanlang yoki Tumanni tanlang':'Выберите город или район',
      'Saqlash':'Сохранить',
      'Ma’lumotlarni kiriting':'Введите данные',
      'Bekor qilish':'Отменить',
      'Diqqat!':'Внимание!',
      'Portlar holati':'Состояние портов',
      'Yaxshi':'Хорошо',
      'Normal':'Нормально',
      'Past':'Низкий',
      'O`chiq':'Включено',
      'Qurilma o`chiq':'Устройство выключено',
      'Kuting!':'Подождите...',
      'Mamlakatlarni qidirish':'Поиск регионов',
      'Qurilma haqida':'Информация о устройстве',
      'Portlar holati haqida':'Информация о состоянии портов',
      'ma’lumotlar':'Данные',
      'Portlar':'Порты',
      'Sozlamalar':'Настройки',
      'Qurilmalar ro‘yxati':'Список устройств',
      'Ma’lumotlar topilmadi':'Данные отсутствуют',
      'Port':'Порт',
      'POE':'ПОЕ',
      'Extend':'Продлевать',
      'Reboot':'Перезагрузить',
      'Power':'Власть',
      'TX':'TX',
      'RX':'RX',
      'Status':'Положение',
      'Qurilmani tahrirlash':'Изменить устройство',
      'Telefon raqamingizni kiriting':'Введите ваш номер телефона:',
      'Biz Tasdiqlash kodini jo‘natamiz':'Отправьте код подтверждения',
      'Telefon raqam':'Номер телефона',
      'Tasdiqlash':'Подтвердить',

      'Qurilma modeli':'Модель устройства',
      'Seriya raqami':'Серийный номер',
      'MAC adress':'MAC Адрес',
      'Ip adress':'IP Адрес',
      'Dasturiy ta’minot':'программное обеспечение',
      'POE kuchlanishi':'POE напряжение',
      'POE quvvati':'POE мощность',
      'Online davri':'Онлайн период',
      'Qurilmani o‘chirib yoqish':'Перезагрузите устройство',

      'Kuzatuvchilar':'Подписчики',
      'Ulashish':'Поделиться',
      'O‘chirish':'Удалить',
      'Jami':'Итого',
      'Yoniq':'Включено',
      'Xato':'Ошибка',
      'Qo‘shimcha ma’lumotlar yo‘q':'Дополнительная информация отсутствует',

      'Loyiha qo‘shish':'Добавить проект',
      'Loyiha nomi':'Название проекта',
      'Qurilma nomi':'Название устройства',
      'Qurilmaning ishlab chiqarish raqami':'Серийный номер устройства',
      'Qurilma paroli':'Пароль устройства',
      'QR Kodni Skaynerlash':'Сканирование QR кода',
      'Loyihani tahrirlash':'Изменить проект',
      'Qo‘shimcha ma’lumot':'Дополнительная информация',
      'Loyihani kuzatuvchilari':'Подписчики проекта',
      'Loyihani ulashish':'Поделиться проектом',
      'Kuzatuvchi telefon raqami':'Номер телефона подписчика',
      'Kuzatuvchi nomi':'Имя подписчика',
      'Loyiha o’chirilsinmi?':'Вы хотите удалить проект?',
      'Qurilma o‘chirilsinmi?':'Вы хотите удалить устройство?',

      // validation
      'Muvaffaqiyatli':'Успешно',
      'Iltimos ulanishni tekshiring!':'Пожалуйста, проверьте соединение!',
      'Hisobingizga kirishda xatolik yuz berdi.':'Ошибка при входе в аккаунт.',
      'Serverga ulanishda xatolik yuz berdi.':'Ошибка подключения к серверу.',
      'Ushbu foydalanuvchi hisobi o‘chirildi.':'Этот аккаунт удален.',
      'Sizda bunday huquq mavjud emas!':'У вас нет такого права!',
      'Ushbu foydalanuvchi allaqachon taklif qilgan.':'Этот пользователь уже приглашен.',
      'Ushbu foydalanuvchi tizimda mavjud emas!':'Этого пользователя нет в системе!',
      'Kiritilgan ma’lumotlar (Masalan, serия raqam) noto‘g‘ri!':'Введенные данные (например, серийный номер) неверны!',
      'Ushbu loyiha boshqa foydalanuvchilarda mavjud.':'Этот проект уже существует у других пользователей.',
      'Bu qurilma online emas.':'Это устройство не в сети.',
      'Ma’lumot o’zgartirildi.':'Информация изменена.',
      'Iltimos hisobingizga qaytadan kiriting.':'Пожалуйста, войдите в аккаунт заново.',
      'Iltimos qaytadan urinib ko‘ring.':'Пожалуйста, попробуйте снова.',
      'Qurilma qayta ishga tushdi.':'Устройство перезапущено.',
      'Loyiha nomini kiriting.':'Введите название проекта.',
      'Qurilma nomini kiriting.':'Введите название устройства.',
      'Qurilmaning ishlab chiqarish raqamini kiriting.':'Введите серийный номер устройства.',
      'Qurilmaning parolini kiriting.':'Введите пароль устройства.',
      'Kuzatuvchi telefon raqami kiriting':'Номер телефона подписчика',
      'Kuzatuvchi nomi kiriting':'Имя подписчика',
      'dialoglar':'Если индикатор желтый или оранжевый, проверьте сетевой кабель и разъем. Попробуйте включить функцию ультра дальнего порта, так как проблема может быть вызвана слишком длинной линией или плохим качеством кабеля.'
    },
    'oz_OZ':{
      'Dilshodjon Haydarov':'Дилшоджон Ҳайдаров',
      'versiya':'Версияси 1.0.0',
      'Loyihalar ro‘yxati':'Лойиҳалар рўйхати',
      'Mening hisobim':'Менинг ҳисобим',
      'Hisobdan chiqish':'Ҳисобдан чиқиш',
      'Dastur mavzusi':'Дастур мавзуси',
      'Dastur tili':'Дастур тили',
      'Foydalanish yo‘riqnomasi':'Фойдаланиш йўриқномаси',
      'Qo‘llab quvvatlash':'Қўллаб-қувватлаш',
      'Dasturni baholash':'Дастурни баҳолаш',
      'Dasturni ulashish':'Дастурни улашиш',
      'Tahrirlash':'Таҳрирлаш',
      'Qidirish':'Қидириш',
      'Tilni tanlang':'Тилни танланг',
      'Bog‘lanish':'Боғланиш',
      'Web sahifa':'Веб саҳифа',
      'Manzil':'Манзил',
      'Qo‘qon shaxar, A.Navoiy, 12 uy.':'Қўқон шаҳар, А.Навоий, 12 уй.',
      'Yuborildi':'Юборилди',
      'Hisobni taxrirlash':'Ҳисобни таҳрирлаш',
      'Ism va familiya':'Исм ва фамилия',
      'Kiriting':'Киритинг',
      'Mamlakat':'Мамлакат',
      'Ism-familiyangizni kiriting':'Исм-фамилиянгизни киритинг',
      'Uzbekistan':'Ўзбекистон',
      'Viloyat':'Вилоят',
      'Shaxar/Tuman':'Шаҳар/Туман',
      'Foydalanuvchi turi':'Фойдаланувчи тури',
      'Xatolik':'Хатолик',
      'Xatolik yuz berdi':'Хатолик юз берди',
      'Iltimos, qayta urinib ko‘ring':'Илтимос, қайта уриниб кўринг',
      'Viloyatni tanlang':'Вилоятни танланг',
      'Shaxarni tanlang yoki Tumanni tanlang':'Шаҳарни ёки Туманни танланг',
      'Saqlash':'Сақлаш',
      'Ma’lumotlarni kiriting':'Маълумотларни киритинг',
      'Bekor qilish':'Бекор килиш',
      'Diqqat!':'Диққат!',
      'Portlar holati':'Портлар ҳолати',
      'Yaxshi':'Яхши',
      'Normal':'Нормал',
      'Past':'Паст',
      'O`chiq':'Ўчиқ',
      'Qurilma o`chiq':'Қурилма ўчиқ',
      'Kuting!':'Кутинг!',
      'Mamlakatlarni qidirish':'Мамлакатларни қидириш',
      'Qurilma haqida':'Қурилма хақида',
      'Portlar holati haqida':'Портлар ҳолати хақида',
      'ma’lumotlar':'Маълумотлар',
      'Portlar':'Портлар',
      'Sozlamalar':'Созламалар',
      'Qurilma modeli':'Қурилма модели',
      'Seriya raqami':'Серия рақами',
      'MAC adress':'MAC адрес',
      'Ip adress':'IP адрес',
      'Dasturiy ta’minot':'Дастурия таъминот',
      'POE kuchlanishi':'ПОЭ кучланиши',
      'POE quvvati':'ПОЭ куввати',
      'Online davri':'Онлайн даври',
      'Qurilmani o‘chirib yoqish':'Қурилмани ўчириб юқиш',
      'Qurilmalar ro‘yxati':'Қурилмалар рўйхати',
      'Ma’lumotlar topilmadi':'Маълумотлар топилмади',
      'Port':'Порт',
      'POE':'ПОЕ',
      'Extend':'Узатиш',
      'Reboot':'Қайта ишга тушириш',
      'Power':'Қувват',
      'TX':'TX',
      'RX':'RX',
      'Status':'Ҳолат',
      'Qurilmani tahrirlash':'Қурилмани таҳрирлаш',
      'Telefon raqamingizni kiriting':'Телефон рақамингизни киритинг:',
      'Biz Tasdiqlash kodini jo‘natamiz':'Биз Тасдиқлаш кодини жўнатамиз',
      'Telefon raqam':'Телефон рақам',
      'Tasdiqlash':'Тасдиқлаш',

      'Kuzatuvchilar':'Кузатувчилар',
      'Ulashish':'Улашиш',
      'O‘chirish':'Ўчириш',
      'Jami':'Жами',
      'Yoniq':'Ёниқ',
      'Xato':'Хато',
      'Qo‘shimcha ma’lumotlar yo‘q':'Қўшимча маълумотлар йўқ',

      'Loyiha qo‘shish':'Лойиҳа қўшиш',
      'Loyiha nomi':'Лойиҳа номи',
      'Qurilma nomi':'Қурилма номи',
      'Qurilmaning ishlab chiqarish raqami':'Қурилманинг ишлаб чиқариш рақами',
      'Qurilma paroli':'Қурилма пароли',
      'QR Kodni Skaynerlash':'ҚР Кодни Скайнерлаш',
      'Loyihani tahrirlash':'Лойиҳани таҳрирлаш',
      'Qo‘shimcha ma’lumot':'Қўшимча маълумот',
      'Loyihani kuzatuvchilari':'Лойиҳани кузатувчилари',
      'Loyihani ulashish':'Лойиҳани улашиш',
      'Kuzatuvchi telefon raqami':'Кузатувчи телефон рақами',
      'Kuzatuvchi nomi':'Кузатувчи номи',
      'Loyiha o’chirilsinmi?':'Лойиҳа ўчирилсинми?',
      'Qurilma o‘chirilsinmi?':'Қурилма ўчирилсинми?',

      // validation
      'Muvaffaqiyatli':'Муваффақиятли',
      'Iltimos ulanishni tekshiring!':'Илтимос уланишни текширинг!',
      'Hisobingizga kirishda xatolik yuz berdi.':'Ҳисобингизга киришда хатолик юз берди.',
      'Serverga ulanishda xatolik yuz berdi.':'Серверга уланишда хатолик юз берди.',
      'Ushbu foydalanuvchi hisobi o‘chirildi.':'Ушбу фойдаланувчи ҳисоби ўчирилди.',
      'Sizda bunday huquq mavjud emas!':'Сизда бундай ҳуқуқ мавжуд эмас!',
      'Ushbu foydalanuvchi allaqachon taklif qilgan.':'Ушбу фойдаланувчи аллақачон таклиф қилган.',
      'Ushbu foydalanuvchi tizимда mavjud emas!':'Ушбу фойдаланувчи тизимда мавжуд эмас!',
      'Kiritilgan ma’lumotlar (Masalan, seriya raqam) noto‘g‘ri!':'Киритилган маълумотлар (Масалан, серия рақам) нотўғри!',
      'Ushbu loyiha boshqa foydalanuvchilarda mavjud.':'Ушбу лойиҳа бошқа фойдаланувчиларда мавжуд.',
      'Bu qurilma online emas.':'Бу қурилма онлайн эмас.',
      'Ma’lumot o’zgartirildi.':'Маълумот ўзгартирилди.',
      'Iltimos hisobingizga qaytadan kiriting.':'Илтимос, ҳисобингизга қайтадан киринг.',
      'Iltimos qaytadan urinib ko‘ring.':'Илтимос қайтадан уриниб кўринг.',
      'Qurilma qayta ishga tushdi.':'Қурилма қайта ишга тушди.',
      'Loyiha nomini kiriting.':'Лойиҳа номини киритинг.',
      'Qurilma nomini kirитинг.':'Қурилма номини киритинг.',
      'Qurilmaning ishlab chiqarish raqamini kiriting.':'Қурилманинг ишлаб чиқариш рақамини киритинг.',
      'Qurilmaning parolini kiriting.':'Қурилманинг паролини киритинг.',
      'Kuzatuvchi telefon raqami kiriting':'Кузатувчи телефон рақами киритинг',
      'Kuzatuvchi nomi kiriting':'Кузатувчи номи киритинг',
      'dialoglar':'Агар индикатор сариқ ёки тўқ сариқ бўлса, тармоқ кабелини ва улагични текширинг. узоқ масофали порт функциясини ёқишга ҳаракат қилиб кўринг, чунки муаммо линиянинг жуда узунлиги ёки кабель сифатининг ёмонлиги билан боғлиқ бўлиши мумкин.'
    }
  };

}